displayName: KevinGimbel Default Headers
summary: A test plugin for Traefik
type: middleware
import: github.com/kevingimbel/traefik-plugin-header
compatibility: TODO
testData:
  headers:
    - key: "de.kevingimbel/version"
      value: "1.0"
